### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by coded1guy**
check it out, is it okay

### CODE REVIEW

**Comment by bamiogunfemi** [comment]
Please create a Pr per feature, don't create a folder for your work place it under the respective folders, add a screenshot of your code and add reviewers

**Comment by bamiogunfemi** [comment]
Your hero looks awesome just use the correct fonts, place under the proper folders and create as a Pr on its own and I'll merge.

**Comment by bamiogunfemi** [comment]
Your register looks awesome just remove a bit of padding from the left. Seems your hero isn't very responsive fix and create a Pr. Amazing job

**Comment by coded1guy** [comment]
OK ma, I would do so.

**Pull request closed without merging**
